### ISSUE TITLE
Book Now: IE only: The content and sidebar menu seems too close to each other that leads to inconsistency fro design specs

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Peregrine-Medical#22]
Afftected : IE only

![book now_06](https://cloud.githubusercontent.com/assets/11186386/7530334/eedb07e8-f578-11e4-9017-d7095f52be31.jpg)

**Comment by genesiscebudigital** [comment]
What version of IE? it's ok in my end

**Comment by dsigue** [comment]
Sorry, I forgot to put the version - It was IE 9 only
